---
fixtures:
  forge_modules:
    inifile:
      repo: "puppetlabs/inifile"
      ref: "4.2.0"
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git://github.com/puppetlabs/provision.git'
