---
fixtures:
  forge_modules:
    ruby_task_helper:
      repo: "puppetlabs/ruby_task_helper"
      ref: "0.5.1"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "4.2.0"
  repositories:
    "stdlib":
      "repo": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "translate":
      "repo": "https://github.com/puppetlabs/puppetlabs-translate"
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: "git://github.com/puppetlabs/provision.git"
    puppet_conf:
      repo: 'https://github.com/puppetlabs/puppet_conf.git'
    common_events_library: 'https://github.com/puppetlabs/puppetlabs-common_events.git'
