.rubocop.yml:
  default_configs:
    inherit_from: .rubocop_todo.yml

Gemfile:
  optional:
    ':development':
      - gem: 'puppet_litmus'
        platforms:
          - ruby
          - mswin
          - mingw
          - x64_mingw
        condition: "ENV['PUPPET_GEM_VERSION'].nil? or ENV['PUPPET_GEM_VERSION'] !~ %r{ 5}"
      - gem: 'hiera-eyaml'
        from_env: 'HIERA_EYAML_GEM_VERSION'
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
      - gem: 'rspec_junit_formatter'
      - gem: 'rb-readline'
        version:
          '= 0.5.5'
        platforms:
          - mswin
          - mingw
          - x64_mingw
      - gem: 'pdk'

.travis.yml:
  delete: true

.gitlab-ci.yml:
  delete: true

Rakefile:
  requires:
  use_litmus_tasks: true

.gitignore:
  required: &ignorepaths
    - '**/litmus_inventory.yaml'
