version: "2.0"

services:
  enterprise:
    image: artifactory.delivery.puppetlabs.net:5000/splunk/splunk:latest
    hostname: splunk_instance
    environment:
      - SPLUNK_START_ARGS=--accept-license
      # The splunkbase credentials are to download and install the Puppet
      # Report Viewer from Splunkbase.
      # We could alternatively download the packaged app from a location
      # like github for testing.
      - SPLUNK_APPS_URL=https://github.com/puppetlabs/TA-puppet-report-viewer/tarball/main
      - SPLUNK_PASSWORD=piepiepie
    volumes:
      # default.yml is a mechanism to load splunk settings that would normally
      # be configured through the ui.
      - ./default.yml:/tmp/defaults/default.yml
    ports:
      # localhost:8000 will bring up the web interface
      - "0.0.0.0:8000:8000"
      # 8088 is the hec endpoint
      - "0.0.0.0:8088:8088"
